SELECT * FROM companies;
SELECT * FROM persons;
SELECT * FROM fates;
SELECT * FROM projects;
SELECT * FROM contracts;
SELECT * FROM requirements;
SELECT * FROM incidents;
SELECT * FROM shifts;
SELECT * FROM project_team;